class1 = int(input("Введите количество учащихся в первом классе: "))
class2 = int(input("Введите количество учащихся во втором классе: "))
class3 = int(input("Введите количество учащихся в третьем классе: "))
total_desks = ((class1 + 1) // 2 + (class2 +1) // 2 + (class3+1) // 2 )
print( total_desks)
